# Commit Stage Workflow
#
# - **Triggers:** Executes on push and pull request events for the main branch.
# - **Environment:** Utilizes `macos-latest` for running tasks, ensuring compatibility with macOS.
# - **Key Tasks:**
#   - **Checkout:** Fetches the latest code from the repository.
#   - **Setup Node.js:** Installs Node.js version 20 for consistency in running Node applications.
#   - **Dependency Installation:** Uses `npm ci` to install project dependencies.
#   - **Code Compilation:** Compiles TypeScript code using `tsc`.
#   - **Testing:** Executes all tests located in the `./tests` directory to verify code functionality.
#   - **Linting:** Runs ESLint to enforce code style and catch potential issues.
#   - **Build:** Builds the project using `npm run build`.
#   - **Artifact Upload:** Uploads the generated `.dmg` file as an artifact, with a retention period of 5 days.
#
# - **Commit Stage Badge:** Generates a visual status badge indicating the success or failure of the commit stage,
#   using green for success and red for failure. The badge is updated based on the outcome of the commit jobs.
#
# This workflow ensures that every commit meets quality standards before it is integrated into the main branch,
# thus maintaining code reliability and readiness for deployment.

name: Commit Stage

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

permissions: write-all

jobs:
  commit:
    name: Commit Stage
    runs-on: macos-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set Up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install Dependencies
        run: npm ci

      - name: Compile Code
        run: npx tsc

      - name: Run Unit Tests
        run: npm run test:unit

      - name: Run Narrow Integration Tests
        run: npm run test:integration

      - name: Run Component Tests
        run: npm run test:component

      - name: Run Contract Provider Verification Tests
        run: npm run test:contract

      - name: Run ESLint
        run: npm run lint

      - name: Build
        run: npm run build

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          retention-days: 5
          name: MongoDB Query Executor
          path: ./release/**/*.dmg

  commit_stage_badge:
    name: Create status badge for workflow
    runs-on: ubuntu-latest
    if: ${{ always() }}
    needs: [commit]
    steps:
      - name: Commit Stage badge (Success)
        if: ${{ !contains(needs.*.result, 'failure') }}
        uses: RubbaBoy/BYOB@v1.3.0
        with:
          NAME: commit_stage
          LABEL: "Commit Stage"
          STATUS: "Success"
          COLOR: green
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Commit Stage badge (Failure)
        if: ${{ contains(needs.*.result, 'failure') }}
        uses: RubbaBoy/BYOB@v1.3.0
        with:
          NAME: commit_stage
          LABEL: "Commit Stage"
          STATUS: "Failure"
          COLOR: red
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
